#!/usr/bin/env python3
"""Compaction *candidate* finder for the vault (stage 1 of 2).

Local, no API key. Surfaces three decay signals; judging the actual edit and
proposing it as a diff is left to a human (or an LLM session) reading the
flagged pages. This script NEVER rewrites pages.

Signals (grounded in agent-memory / RAG compaction prior art — A-MEM evolution,
Mem0 ADD/UPDATE/MERGE/NOOP, RAG dedup-by-lineage):
  - MERGE   : two pages with very high page-vector cosine (redundant overlap).
  - UPDATE  : correction-heavy pages (many strikethroughs / retraction markers)
              — collapse resolved retractions into current truth plus a terse
              changelog. (highest ROI for a correction-heavy vault)
  - SPLIT   : oversized pages (multi-topic sprawl) — chunk into focused pages.

  python -m llm_wiki.hygiene.compact [--merge-tau 0.85] [--size-kb 12] [--corrections 6]

Writes .compaction.md (a review list). Reuses contradict.py's page vectors.
"""
from __future__ import annotations

import argparse

import numpy as np

from llm_wiki.hygiene.contradict import CORRECTION, is_companion, page_vectors
from llm_wiki.paths import content_dirs, content_root, vault_root

VAULT = vault_root()

MIN_SENTENCE_CHARS = 40   # shorter lines are headings/bullets, not evidence of copying
MIN_OVERLAP = 0.30        # share of the shorter page's sentences that must be identical

OUT = content_root() / ".compaction.md"


def sentence_overlap(a: str, b: str) -> float:
    """Fraction of the SHORTER page's substantial sentences that appear verbatim
    in the other. This is the redundancy signal; cosine is not.

    Measured 2026-07-31: every cosine>=0.85 pair shared at most 2 identical
    sentences out of 48-116. The corpus is topically dense, so cosine tracks
    subject matter — two verdict pages for the same investigation read alike
    without restating each other.
    Normalising by the shorter page catches the real case worth merging: one
    page wholly contained in another.
    """
    import re as _re

    def sents(t: str) -> set:
        t = t.split("\n---", 1)[-1]
        return {_re.sub(r"\s+", " ", x).strip()
                for x in _re.split(r"[.\n]", t) if len(x.strip()) >= MIN_SENTENCE_CHARS}

    A, B = sents(a), sents(b)
    if not A or not B:
        return 0.0
    return len(A & B) / min(len(A), len(B))


def is_merge_candidate(cosine: float, a: str, b: str, tau: float = 0.85,
                       min_overlap: float = MIN_OVERLAP) -> bool:
    """MERGE requires BOTH a high cosine and real textual redundancy.

    Cosine alone had 0% precision (19/19 false positives), and a false MERGE
    is expensive: it sends a human to collapse distinct artifacts.
    """
    return cosine >= tau and sentence_overlap(a, b) >= min_overlap


def page_path(_id: str):
    for base in content_dirs(VAULT):
        matches = sorted(base.rglob(f"{_id}.md"))
        if matches:
            return matches[0]
    return None


def _read(_id: str) -> str:
    p = page_path(_id)
    return p.read_text(encoding="utf-8") if p else ""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--merge-tau", type=float, default=0.85, help="min cosine for MERGE candidate")
    ap.add_argument("--size-kb", type=float, default=12.0, help="page size (KB) over which to flag SPLIT")
    ap.add_argument("--corrections", type=int, default=6, help="# correction markers over which to flag UPDATE")
    args = ap.parse_args()

    ids, mat, info = page_vectors()
    idx = {i: r for r, i in enumerate(ids)}

    oversized, correction_heavy = [], []
    for _id in ids:
        p = page_path(_id)
        if not p:
            continue
        text = p.read_text(encoding="utf-8")
        kb = len(text.encode()) / 1024
        ncorr = len(CORRECTION.findall(text))
        if kb > args.size_kb:
            oversized.append((kb, _id))
        if ncorr >= args.corrections:
            correction_heavy.append((ncorr, _id))
    oversized.sort(reverse=True)
    correction_heavy.sort(reverse=True)

    sims = mat @ mat.T
    np.fill_diagonal(sims, -1.0)
    seen, merges = set(), []
    for r, a in enumerate(ids):
        for c in np.argsort(-sims[r])[:4]:
            s = float(sims[r, c])
            if s < args.merge_tau:
                break  # neighbours are sorted by cosine, so the rest are lower
            if not is_merge_candidate(s, _read(ids[r]), _read(ids[c]), args.merge_tau):
                continue  # topically close but not redundant — NOT a merge
            x, y = sorted([a, ids[c]])
            if (x, y) in seen or is_companion(x, y):
                continue
            seen.add((x, y))
            merges.append((s, x, y))
    merges.sort(reverse=True)

    L = ["# Compaction candidates", "",
         "GENERATED by `python -m llm_wiki.hygiene.compact` — **candidates only.** Judging and proposing",
         "a diff is left to a human (or an LLM session); **nothing here is applied",
         "automatically**. Facts are archived, never deleted.",
         f"threshold merge_tau={args.merge_tau} · size>{args.size_kb}KB · corrections>={args.corrections}", ""]

    L += [f"## UPDATE (fold retractions) — {len(correction_heavy)} page(s), highest ROI"]
    for n, i in correction_heavy:
        L += [f"- [ ] [[{i}]] · {n} correction marker(s) — rewrite the overturned parts as current "
              f"truth plus a trailing changelog. {info[i].get('summary', '')[:80]}"]
    L += ["", f"## MERGE (redundant overlap) — {len(merges)} pair(s)"]
    for s, a, b in merges:
        L += [f"- [ ] [{s:.3f}] [[{a}]] <-> [[{b}]] — fold the overlap into one page and redirect "
              f"the other (status:superseded + link)"]
    L += ["", f"## SPLIT (oversized) — {len(oversized)} page(s)"]
    for kb, i in oversized:
        L += [f"- [ ] [[{i}]] · {kb:.1f}KB — if multi-topic, split into focused pages. "
              f"{info[i].get('summary', '')[:80]}"]

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"UPDATE {len(correction_heavy)} · MERGE {len(merges)} · SPLIT {len(oversized)} -> {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
