#!/usr/bin/env python3
"""Contradiction *candidate* detector for the vault (stage 1 of 2).

Local, no API key. This finds topically-overlapping page PAIRS — the cheap
recall half. It does NOT decide whether they actually contradict; that
judgment is left to a human (or an LLM session) reading both pages and marking
`status: superseded` + links when a real conflict is confirmed. This script
never rewrites pages.

Method: page vector = mean of its chunk embeddings (renormalized); cosine
between pages; emit pairs above a similarity threshold. High similarity =
same topic = *worth checking* for conflicting claims (e.g. one page's
corrected fact vs another page still asserting the old one).

  python -m llm_wiki.hygiene.contradict [--tau 0.72] [--topk 3] [--changed id1,id2]

Writes .contradictions.md (a review list). --changed limits seeds to those
pages (for incremental use inside ingest).
"""
from __future__ import annotations

import argparse
import json
import re

import numpy as np

from llm_wiki.paths import content_dirs, content_root, vault_root

VAULT = vault_root()
EMB = content_root() / ".embeddings"
OUT = content_root() / ".contradictions.md"

# Retraction/correction cues, Korean and English mixed on purpose — the vault
# writes both, and a page carrying either has overturned some claim, so pairs
# touching it are higher-yield contradiction candidates.
CORRECTION = re.compile(r"~~|정정|오판|철회|supersed|아님\)|취소선|deprecat|반박|폐기")


def _page_path(_id: str):
    for base in content_dirs(VAULT):
        matches = sorted(base.rglob(f"{_id}.md"))
        if matches:
            return matches[0]
    return None


def has_correction(_id: str) -> bool:
    path = _page_path(_id)
    return bool(path and CORRECTION.search(path.read_text(encoding="utf-8")))


def is_companion(a: str, b: str) -> bool:
    """Same-topic sibling docs (planning/execution/interview, phaseX-Y-*) are
    expected to be similar and are NOT contradictions — skip them."""
    ta, tb = a.split("-"), b.split("-")
    return ta[:2] == tb[:2] and len(ta) >= 2  # share first 2 kebab tokens


def page_vectors():
    vecs = np.load(EMB / "vectors.npy")
    meta = json.loads((EMB / "meta.json").read_text(encoding="utf-8"))
    by_page: dict[str, list[int]] = {}
    info: dict[str, dict] = {}
    for i, m in enumerate(meta):
        by_page.setdefault(m["id"], []).append(i)
        info.setdefault(m["id"], m)
    ids = list(by_page)
    mat = np.zeros((len(ids), vecs.shape[1]), dtype=np.float32)
    for r, _id in enumerate(ids):
        v = vecs[by_page[_id]].mean(axis=0)
        mat[r] = v / (np.linalg.norm(v) + 1e-9)
    return ids, mat, info


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tau", type=float, default=0.78, help="min page-page cosine to flag")
    ap.add_argument("--topk", type=int, default=3, help="nearest neighbors per page")
    ap.add_argument("--changed", help="comma-separated ids to seed from (default: all)")
    ap.add_argument("--only-corrected", action="store_true", help="only pairs touching a corrected page")
    args = ap.parse_args()

    ids, mat, info = page_vectors()
    idx = {i: r for r, i in enumerate(ids)}
    sims = mat @ mat.T
    np.fill_diagonal(sims, -1.0)

    seeds = [s for s in (args.changed.split(",") if args.changed else ids) if s in idx]
    corrected = {i for i in ids if has_correction(i)}
    seen, pairs = set(), []
    for s in seeds:
        r = idx[s]
        for c in np.argsort(-sims[r])[: args.topk + 3]:  # room after companion filter
            sim = float(sims[r, c])
            if sim < args.tau:
                break
            a, b = sorted([s, ids[c]])
            if (a, b) in seen or is_companion(a, b):
                continue
            seen.add((a, b))
            flag = (a in corrected) or (b in corrected)
            pairs.append((sim, a, b, flag))
    # corrected-involved pairs first, then by similarity
    pairs.sort(key=lambda x: (-int(x[3]), -x[0]))
    if args.only_corrected:
        pairs = [p for p in pairs if p[3]]

    lines = [
        "# Contradiction candidates",
        "",
        "GENERATED by `python -m llm_wiki.hygiene.contradict` — **candidates only, not confirmed.**",
        "Judging and acting on a pair means reading both pages and deciding which,",
        "if either, is stale.",
        f"threshold tau={args.tau} · topk={args.topk} · {len(pairs)} candidate pair(s)",
        "",
    ]
    for sim, a, b, flag in pairs:
        mark = " (correction present)" if flag else ""
        lines += [
            f"## [{sim:.3f}]{mark} [[{a}]] <-> [[{b}]]",
            "- [ ] Verdict: do these actually contradict? If so, which is current?",
            f"  - A `{a}` — {info[a].get('summary', '')}",
            f"  - B `{b}` — {info[b].get('summary', '')}",
            "",
        ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(pairs)} candidate pair(s) (tau={args.tau}) -> {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
