#!/usr/bin/env python3
"""Regenerate per-project agent memory (the hot cache) from the vault (canonical).

The vault is the single source of truth. Each agent runtime keeps a per-project
memory directory; this script makes those a thin pointer layer into the vault so
the tiers never drift:

  Claude: ~/.claude/projects/<slug>/memory
  Codex:  ~/.codex/projects/<slug>/memory

  1. MEMORY.md — replaces the managed block between `<!-- WIKI:START -->` and
     `<!-- WIKI:END -->` with one pointer line per vault page tagged for this
     project. Everything outside the markers (feedback_*, user memories) is
     preserved untouched — those are personal, and this script does not own them.
  2. Promoted files — for each vault page carrying `cache_stub: <filename>`,
     the matching <memory>/<filename> is rewritten as a thin stub pointing at the
     canonical vault page. Non-promoted memory files are left alone.

Nothing here calls an LLM; it is pure text templating. Run after editing vault
pages (typically right after `wiki-index`).

  python -m integrations.agent_memory.sync_cache --project /abs/path --target claude|codex|both
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

from llm_wiki.paths import VAULT_ROOT, content_root, index_path

INDEX_PATH = index_path()
# Pointer lines address pages by their content-root-relative `path`, so the
# prefix must be the CONTENT root, not the directory wiki.toml lives in.
CONTENT_ROOT = content_root()
START = "<!-- WIKI:START -->"
END = "<!-- WIKI:END -->"
TARGETS = ("claude", "codex")


def memory_dir(project: Path, target: str = "claude", home: Path = None) -> Path:
    """<home>/.<target>/projects/<slug>/memory, slug = abspath with '/' -> '-'."""
    if target not in TARGETS:
        raise ValueError(f"unknown target {target!r}; expected one of {list(TARGETS)}")
    base = Path(home) if home is not None else Path.home()
    slug = str(project).replace("/", "-")
    return base / f".{target}" / "projects" / slug / "memory"


def resolve_targets(target: str) -> list:
    if target == "both":
        return list(TARGETS)
    if target not in TARGETS:
        raise ValueError(f"unknown target {target!r}; expected claude|codex|both")
    return [target]


def load_index() -> list:
    data = yaml.safe_load(INDEX_PATH.read_text(encoding="utf-8"))
    return data.get("entries", [])


def entries_for_project(entries: list, project_name: str) -> list:
    return [e for e in entries if project_name in (e.get("projects") or [])]


def with_cache_stubs(entries: list, vault: Path = VAULT_ROOT) -> list:
    """index.yaml carries no cache_stub field — read it back off the pages."""
    from llm_wiki import build_index

    root = content_root(vault)
    out = []
    for e in entries:
        fm = build_index.parse_frontmatter(root / e["path"]) or {}
        if fm.get("cache_stub"):
            out.append({**e, "cache_stub": fm["cache_stub"]})
    return out


def pointer_line(e: dict) -> str:
    return (f"- [[{e['id']}]] ({e['layer']}/{e.get('domain', '-')}) — {e['summary']} "
            f"→ `{CONTENT_ROOT}/{e['path']}`")


def stub_body(e: dict) -> str:
    return (
        f"---\nname: {e['id']}\ndescription: {e['summary']}\nmetadata:\n  type: pointer\n---\n\n"
        f"-> canonical has been promoted to the global wiki: `{CONTENT_ROOT}/{e['path']}`\n\n"
        f"{e['summary']}\n\n"
        f"(This file is a pointer stub generated by sync_cache.py — read the vault page for detail.)\n"
    )


def render_memory_md(existing: str, entries: list) -> str:
    """Replace only the managed block; preserve everything else verbatim."""
    block = "\n".join([
        START,
        "<!-- GENERATED by integrations.agent_memory.sync_cache — do not edit by hand -->",
        "## Canonical wiki (source of truth)",
        *[pointer_line(e) for e in entries],
        END,
    ])
    stubs = {e["cache_stub"] for e in entries if e.get("cache_stub")}
    text = re.sub(re.escape(START) + r".*?" + re.escape(END) + r"\n?", "",
                  existing, flags=re.DOTALL)
    # drop stale hand-written bullet lines pointing at now-promoted memory files
    kept = [ln for ln in text.splitlines() if not any(f"]({s})" in ln for s in stubs)]
    personal = "\n".join(kept).strip()
    # Without the emptiness check, a file that is ONLY the managed block grows two
    # leading blank lines on every sync — so repeated syncs would never converge.
    return (personal + "\n\n" + block + "\n") if personal else (block + "\n")


def sync_one(mem_dir: Path, entries: list, dry: bool) -> list:
    lines = [f"memory : {mem_dir}"]
    md = mem_dir / "MEMORY.md"
    existing = md.read_text(encoding="utf-8") if md.exists() else ""
    new = render_memory_md(existing, entries)
    if dry:
        lines.append(f"[dry] MEMORY.md: would write {len(entries)} pointer line(s)")
        for e in entries:
            if e.get("cache_stub"):
                state = "exists→slim" if (mem_dir / e["cache_stub"]).exists() else "create"
                lines.append(f"[dry] {e['cache_stub']}: {state}")
        return lines

    mem_dir.mkdir(parents=True, exist_ok=True)
    md.write_text(new, encoding="utf-8")
    lines.append(f"MEMORY.md: wrote {len(entries)} pointer line(s)")
    for e in entries:
        if e.get("cache_stub"):
            (mem_dir / e["cache_stub"]).write_text(stub_body(e), encoding="utf-8")
            lines.append(f"{e['cache_stub']}: slimmed to pointer")
    return lines


def sync_project(project: Path, target: str = "claude", home: Path = None,
                 entries: list = None, dry: bool = False) -> list:
    out = []
    for one in resolve_targets(target):
        out.extend(sync_one(memory_dir(Path(project), one, home), entries or [], dry))
    for line in out:
        print(line)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", required=True,
                    help="absolute path of the project whose memory to sync")
    ap.add_argument("--target", default="claude", choices=["claude", "codex", "both"])
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    project = Path(args.project).resolve()
    tagged = entries_for_project(load_index(), project.name)
    # Only pages that originated from this project's auto-memory belong in the hot
    # cache (they replace the old per-project memory files). Most vault pages were
    # never sourced from auto-memory to begin with -> vault-only, discoverable via
    # index.yaml rather than promoted into a project's memory.
    promoted = with_cache_stubs(tagged)
    if not promoted:
        print(f"⚠ no promoted (cache_stub) pages for {project.name} — nothing to sync",
              file=sys.stderr)

    print(f"project: {project}\ntagged : {len(tagged)}  promoted(cache): {len(promoted)}")
    sync_project(project, target=args.target, entries=promoted, dry=args.dry_run)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
