#!/usr/bin/env python3
"""Rebuild and validate the vault's index.yaml from per-page YAML frontmatter.

The page frontmatter is the single source of truth; index.yaml is generated.
Run `--check` (e.g. in a git pre-commit hook or CI) to fail on any violation
without writing.

`--check` compares the *rendered bytes* against the committed file, not just
"does the frontmatter validate". A syntactically valid index.yaml that no longer
matches the pages is exactly the drift that silently poisons recall, so it is a
hard error here.

Contract (see docs/CONFIGURATION.md):
  - filename stem MUST equal `id` (so Obsidian [[id]] wikilinks resolve)
  - required fields: id, layer, projects, tags, confidence, status, summary
  - `domain` required when layer == "domain"
  - `links` (optional) must reference existing ids
"""
from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from pathlib import Path

import yaml

from llm_wiki import config
from llm_wiki.paths import VAULT_ROOT, content_paths, index_path, relative

WIKILINK_RE = re.compile(r"\[\[([^\]|#]+)")  # [[id]], [[id|alias]], [[id#anchor]]
_FENCE_RE = re.compile(r"```.*?```", re.DOTALL)
_INLINE_RE = re.compile(r"`[^`\n]*`")  # exclude [[x]] written as documentation in code spans
_KEBAB_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
_ISO_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
_FM_SCALAR_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_-]*):[ \t]+(\S.*)$")
_BURIED_RE = re.compile(r"^---[ \t]*\n(?:[a-z_]+:.*\n)*?id:[ \t]+(\S+)", re.MULTILINE)

INDEX_PATH = index_path()
INDEX_HEADER = "# GENERATED by wiki-index — edit page frontmatter, not this file.\n"
STALE_INDEX = "index.yaml differs from canonical page frontmatter"

CONFIDENCE = {"confirmed", "provisional"}
STATUS = {"active", "superseded"}
LIST_FIELDS = ["projects", "tags", "links"]
TEXT_FIELDS = ["id", "layer", "domain", "confidence", "status", "summary", "cache_stub"]


def parse_frontmatter(path: Path) -> dict | None:
    """Return the YAML frontmatter dict, or None if the file has no `---` block."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    data = yaml.safe_load(text[3:end])
    return data if isinstance(data, dict) else None


def collect_pages(vault: Path = VAULT_ROOT) -> list[tuple[Path, dict]]:
    return [(p, parse_frontmatter(p) or {}) for p in content_paths(vault)]


def _frontmatter_block(text: str) -> tuple[str, str]:
    """Split a page into (frontmatter block, body). Both empty if there is none."""
    if not text.startswith("---"):
        return "", text
    end = text.find("\n---", 3)
    if end == -1:
        return "", text
    return text[3:end], text[end + 4:]


def comment_truncated_fields(path: Path) -> list[tuple[str, int, int]]:
    """Frontmatter scalars silently cut short by an unquoted ' #'.

    In YAML a `#` preceded by whitespace starts a comment, so
    `summary: measured in PR #527 — …` parses to `measured in PR` and the rest
    never reaches index.yaml. It is valid YAML, so neither the parser nor the
    schema check notices; the page just loses most of its summary, which
    contextual retrieval prefixes onto every one of its chunks.

    Returns (field, parsed_len, raw_len) per affected scalar.
    """
    block, _ = _frontmatter_block(path.read_text(encoding="utf-8"))
    if not block:
        return []
    try:
        fm = yaml.safe_load(block)
    except yaml.YAMLError:
        return []  # unparseable frontmatter is already an error elsewhere
    if not isinstance(fm, dict):
        return []
    out: list[tuple[str, int, int]] = []
    for line in block.splitlines():
        m = _FM_SCALAR_RE.match(line)
        if not m:
            continue
        field, raw = m.group(1), m.group(2).rstrip()
        if raw[0] in "'\"|>&*!{[":
            continue  # quoted or non-plain scalar: '#' there is data, not a comment
        if " #" not in raw:
            continue
        parsed = fm.get(field)
        if parsed is None:
            out.append((field, 0, len(raw)))
        elif isinstance(parsed, str) and len(parsed) < len(raw):
            out.append((field, len(parsed), len(raw)))
    return out


def buried_page_ids(path: Path) -> list[str]:
    """ids of extra frontmatter blocks concatenated into one file's body.

    `index.yaml` is built from the FIRST block only, so every later block is
    invisible to the index, to recall, and to the link graph while still sitting
    in the vault looking filed. Fenced code blocks are excluded so a page may
    document frontmatter as an example.
    """
    _, body = _frontmatter_block(path.read_text(encoding="utf-8"))
    return _BURIED_RE.findall(_FENCE_RE.sub("", body))


def _type_errors(rel: str, fm: dict) -> list[str]:
    """Reject fields that are the right *name* but the wrong shape.

    `projects: repo` (a bare string) instead of `projects: [repo]` still passes a
    presence check, then quietly becomes a 4-character-per-entry list downstream
    in retrieval filters. Catch it at the schema boundary instead.
    """
    errors: list[str] = []
    for field in LIST_FIELDS:
        if field not in fm or fm[field] is None:
            continue
        value = fm[field]
        if not isinstance(value, list):
            errors.append(f"{rel}: {field} must be a list of strings, got {type(value).__name__}")
            continue
        if not all(isinstance(x, str) and x.strip() for x in value):
            errors.append(f"{rel}: {field} must be a list of non-empty strings")
    for field in TEXT_FIELDS:
        if field in fm and fm[field] is not None and not isinstance(fm[field], str):
            errors.append(f"{rel}: {field} must be a string, got {type(fm[field]).__name__}")
    updated = fm.get("updated")
    if updated is not None:
        # PyYAML already parses a bare 2026-07-31 into a date; a quoted one stays
        # a string. Accept both, reject prose.
        ok = isinstance(updated, (dt.date, dt.datetime)) or (
            isinstance(updated, str) and _ISO_DATE_RE.match(updated)
        )
        if not ok:
            errors.append(f"{rel}: updated must be an ISO date (YYYY-MM-DD), got {updated!r}")
    return errors


def validate(pages: list[tuple[Path, dict]], vault: Path = VAULT_ROOT) -> list[str]:
    cfg = config.load(vault)
    errors: list[str] = []
    ids: dict[str, Path] = {}
    for path, fm in pages:
        rel = relative(path, vault)
        if not fm:
            errors.append(f"{rel}: missing or unparseable YAML frontmatter")
            continue
        for field in cfg.required:
            if field not in fm or fm[field] in (None, "", []):
                errors.append(f"{rel}: missing required field '{field}'")
        errors.extend(_type_errors(rel, fm))
        for field, parsed_len, raw_len in comment_truncated_fields(path):
            errors.append(
                f"{rel}: '{field}' is truncated by an unquoted ' #' — YAML starts a comment "
                f"there, so only {parsed_len} of {raw_len} chars reach index.yaml. "
                f"Quote the value: {field}: '…'")
        buried = buried_page_ids(path)
        if buried:
            errors.append(
                f"{rel}: {len(buried)} page(s) buried in this file's body "
                f"({', '.join(buried[:3])}{'…' if len(buried) > 3 else ''}) — the index is built "
                f"from the first frontmatter block only, so these are invisible to recall. "
                f"Split each into its own <id>.md")
        _id = fm.get("id")
        if isinstance(_id, str) and _id:
            if not _KEBAB_RE.match(_id):
                errors.append(f"{rel}: id must be kebab-case ([a-z0-9] joined by single '-'), got '{_id}'")
            if path.stem != _id:
                errors.append(f"{rel}: filename stem != id ('{path.stem}' vs '{_id}')")
            if _id in ids:
                errors.append(f"{rel}: duplicate id '{_id}' (also {relative(ids[_id], vault)})")
            ids[_id] = path
        if fm.get("layer") not in cfg.layers:
            errors.append(f"{rel}: layer '{fm.get('layer')}' not in {sorted(cfg.layers)}")
        if fm.get("layer") == "domain":
            if "domain" not in fm:
                errors.append(f"{rel}: layer=domain requires a `domain` field")
            elif cfg.domains and fm["domain"] not in cfg.domains:
                errors.append(f"{rel}: domain '{fm.get('domain')}' not in {sorted(cfg.domains)}")
        if fm.get("confidence") not in CONFIDENCE:
            errors.append(f"{rel}: confidence '{fm.get('confidence')}' not in {sorted(CONFIDENCE)}")
        if fm.get("status") not in STATUS:
            errors.append(f"{rel}: status '{fm.get('status')}' not in {sorted(STATUS)}")
    # link resolution (second pass, after all ids known)
    for path, fm in pages:
        rel = relative(path, vault)
        links = fm.get("links") or []
        if not isinstance(links, list):
            continue  # already reported as a type error
        for link in links:
            if link not in ids:
                errors.append(f"{rel}: link '{link}' does not resolve to any page id")
    return errors


def graph_warnings(pages: list[tuple[Path, dict]], vault: Path = VAULT_ROOT) -> list[str]:
    """Non-fatal link-graph hygiene signals.

    `python -m llm_wiki.reports.graph_report` produces the full report; this is
    the subset worth printing on every index build. Body `[[wikilink]]`s that
    resolve to no page id are the actionable regression signal — a canonical page
    must not link to something that is not a page in this vault (a note kept
    outside the content dirs, a renamed id, a typo). Orphan count is
    informational."""
    ids = {fm.get("id") for _, fm in pages if fm.get("id")}
    indeg = {i: 0 for i in ids}
    dangling: list[str] = []
    for path, fm in pages:
        _id = fm.get("id")
        text = _INLINE_RE.sub("", _FENCE_RE.sub("", path.read_text(encoding="utf-8")))
        targets = {m.strip() for m in WIKILINK_RE.findall(text)}
        targets |= {str(x).strip() for x in (fm.get("links") or [])}
        targets.discard(_id)
        for t in sorted(targets):
            if t in ids:
                indeg[t] += 1
            else:
                dangling.append(f"{_id} → [[{t}]] (no such page)")
    warns = [f"dangling wikilink: {d}" for d in dangling]
    orphans = sum(1 for i in ids if indeg[i] == 0)
    if ids:
        warns.append(f"orphans (0 inbound): {orphans}/{len(ids)} ({orphans * 100 // len(ids)}%)")
    return warns


def build_index(pages: list[tuple[Path, dict]], vault: Path = VAULT_ROOT) -> dict:
    entries = []
    for path, fm in pages:
        if not fm:
            continue
        updated = fm.get("updated")
        entry = {
            "id": fm.get("id"),
            "layer": fm.get("layer"),
            "path": relative(path, vault),
            "projects": fm.get("projects", []),
            "tags": fm.get("tags", []),
            "confidence": fm.get("confidence"),
            "status": fm.get("status"),
            "updated": updated,
            "summary": fm.get("summary"),
        }
        if fm.get("layer") == "domain":
            entry["domain"] = fm.get("domain")
        if fm.get("links"):
            entry["links"] = fm["links"]
        entries.append(entry)
    entries.sort(key=lambda e: (e["layer"], e.get("domain", ""), e["id"]))
    return {"version": 2, "scope": "global", "entries": entries}


def render_index(vault: Path = VAULT_ROOT) -> str:
    """The exact bytes index.yaml must contain for this vault. Raises on invalid pages."""
    pages = collect_pages(vault)
    errors = validate(pages, vault)
    if errors:
        raise ValueError("\n".join(errors))
    return INDEX_HEADER + yaml.safe_dump(
        build_index(pages, vault), allow_unicode=True, sort_keys=False, width=1000
    )


def write_index(vault: Path = VAULT_ROOT, out_path: Path | None = None) -> int:
    path = out_path if out_path is not None else index_path(vault)
    rendered = render_index(vault)
    path.write_text(rendered, encoding="utf-8")
    return len(yaml.safe_load(rendered)["entries"])


def check_index(vault: Path = VAULT_ROOT, out_path: Path | None = None) -> list[str]:
    """Empty list iff the committed index.yaml is byte-identical to a fresh render."""
    path = out_path if out_path is not None else index_path(vault)
    expected = render_index(vault)
    actual = path.read_text(encoding="utf-8") if path.exists() else ""
    return [] if actual == expected else [STALE_INDEX]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="validate only; do not write")
    ap.add_argument("--vault", type=Path, default=VAULT_ROOT,
                    help="vault config root, i.e. the directory holding wiki.toml "
                         "(default: the resolved WIKI_VAULT / nearest ancestor)")
    args = ap.parse_args()

    vault = args.vault.resolve()
    out_path = index_path(vault)

    pages = collect_pages(vault)
    errors = validate(pages, vault)
    if errors:
        print(f"ERROR: {len(errors)} validation error(s):", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        if pages and all(parse_frontmatter(path) is None for path, _ in pages):
            print("NOTE: `wiki-index` is the legacy frontmatter indexer. For a plain-Markdown "
                  "v2 vault, skip it and run `wiki-concepts build`, then `wiki-net build`.",
                  file=sys.stderr)
        return 1

    for w in graph_warnings(pages, vault):
        print(f"WARNING: {w}", file=sys.stderr)

    if args.check:
        drift = check_index(vault, out_path)
        if drift:
            print(f"ERROR: {drift[0]} - run `wiki-index`", file=sys.stderr)
            return 1
        print(f"OK: {len(pages)} pages valid, index.yaml up to date (check-only)")
        return 0

    n = write_index(vault, out_path)
    print(f"OK: wrote index.yaml ({n} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
